#ifndef GOB_JSON_VERSION_HPP
#define GOB_JSON_VERSION_HPP

#define GOB_JSON_VERSION_MAJOR 0
#define GOB_JSON_VERSION_MINOR 0
#define GOB_JSON_VERSION_PATCH 2

#define GOB_JSON_VERSION_STRINGIFY_AGAIN(x) #x
#define GOB_JSON_VERSION_STRINGIFY(x) GOB_JSON_VERSION_STRINGIFY_AGAIN(x)

#define GOB_JSON_VERSION_VALUE ((GOB_JSON_VERSION_MAJOR << 16) | (GOB_JSON_VERSION_MINOR << 8) | (GOB_JSON_VERSION_PATCH))
#define GOB_JSON_VERSION_STRING GOB_JSON_VERSION_STRINGIFY(GOB_JSON_VERSION_MAJOR.GOB_JSON_VERSION_MINOR.GOB_JSON_VERSION_PATCH)

#endif
